### ISSUE TITLE
 { :0 } causes Fatal Error

### ISSUE THREAD

**Issue by luizbills** [hjson/hjson-php#13]
```
{
  :0
}
```

causes `Fatal error: Cannot access empty property in .../src/HJSON/HJSONParser.php on line 204` instead of a exception with message `Error: Found ':' but no key name`

**Comment by peter279k** [comment]
@luizbills, it looks like it's the empty key name and the `hjson-php` throw the exception to warn you.

@dqsully, I think it's not the issue and this issue can be closed :smile:.

**Comment by peter279k** [comment]
@dqsully, thank you for your reply. I think it's okay to throw the exception :).

I reopen this issue.

**Comment by trobro** [comment]
Was fixed by #15, throws an exception as it should.
