### ISSUE TITLE
UTF8

### ISSUE THREAD

**Issue by pinkladywithcoco** [hjson/hjson-php#14]
Cant use danish characters: Æ, Ø and Å.

**Comment by sustained** [comment]
This is also an issue for me, I'm working with Swedish characters and the parser chokes on them.

`ÄäÅåÖöÉé`

**Comment by sustained** [comment]
It is worth noting that it works fine on [the website](https://hjson.org/try.html).

**Comment by dqsully** [comment]
Sorry about the silence. I'm talking a look at this now.

**Comment by sustained** [comment]
No worries, thank you for taking a look at it!
