### ISSUE TITLE
PHP 5.6 and 7.0 EOL

### ISSUE THREAD

**Issue by dqsully** [hjson/hjson-php#20]
PHP versions 5.6 and 7.0 are officially unsupported now. Should we stop supporting them as well?

In my PR #19, I made some changes to be compatible with the latest versions of PHP and phpunit, but it broke PHP 7.0 and 5.6 compatibility. It would be easier overall to stop supporting the older versions, but I don't know, is anyone still using this library with an old PHP version?

**Comment by dqsully** [comment]
http://php.net/supported-versions.php

**Comment by sustained** [comment]
Personally I'm using only PHP 7.3.2 both locally and in production. :+1:

**Comment by peter279k** [comment]
I think it should drop `php-5.6` for the future stable releases :).

**Comment by TigersWay** [comment]
Not sure how many are still using this library with PHP 5.6, but I do...  Yes, sadly and unbelievably some hosters have not upgraded their services.
But please, make it clear and go on, I'm probably the only one!

**Comment by peter279k** [comment]
@TigersWay, thank you for your reply.

Maybe we can have the two different stable releases.

One is about supporting older PHP versions, and another one supports `php-7.1` version at least.

And it can let developers use this latest package version to run on older PHP version environment.

**Comment by TigersWay** [comment]
Honestly not sure how many we are :-) I personally have no trouble to go back to json and put my comments in another file, if I ever need to update.

**Comment by mathiasrw** [comment]
You will die if you keep giving energy to old versions. When will it stop? You still support php3?

I suggest making it clear that when ever a php version ends up on http://php.net/eol.php one can no longer expect hjson to work correctly.

**Comment by peter279k** [comment]
@mathiasrw, I know that.

Perhaps we can try to keep the old PHP versions for thew while.

And drop them support in the future.

These versions (`php-5.6` and `php-7.0`) have been EOL recently and I think it should not be very quick to drop them at this time.

**Comment by mathiasrw** [comment]
I have no skin in the came, but for your own reason, I suggest you make a graveyard section at the readme describing what (previous) version of HJSON-php one should use if you are running deprecated version X of PHP (while stating that for safety reasons people really should upgrade)

**Comment by TigersWay** [comment]
@mathiasrw Just remember it took 2 years for most of webhosters to give access to PHP 7. In a lot of countries around me, most national webhosters still only offer PHP 5.x... And some of us have to deal with that for little local customers.

**Comment by trobro** [comment]
Our current code base does support PHP 5.6 even after #19 was merged. Closing this for now.
