### ISSUE TITLE
Very slow on large data

### ISSUE THREAD

**Issue by chrisputnam9** [hjson/hjson-php#24]
Curious why - will dig in a bit and generate a test file to replicate at the very least.

**Comment by chrisputnam9** [comment]
Added a test file here, and starting to dig through - tips appreciated, otherwise, I'll keep working my way through to understand why it's slow: https://github.com/chrisputnam9/hjson-php/tree/feature/testing-large-file

**Comment by chrisputnam9** [comment]
XDebug profiler shows that mb_strcut is taking the most time - that makes sense to me, because it's being used over and over on the same string (the JSON being parsed).  Thinking maybe using mb_split at the start, then working through the array of characters *might* be faster... or another option might be pulling characters off the string one at a time, and maintaining what's left of the string in memory.  @Connodore do you have any quick insight on this?

**Comment by chrisputnam9** [comment]
Should be fairly easy to do some testing on a few different methods if no one is sure :D

**Comment by chrisputnam9** [comment]
Ooooooh, maybe a Queue would be more efficient... have to check if there are any cases where we need to look back at characters we've passed...

**Comment by chrisputnam9** [comment]
Did a fair bit of testing - preg_split with /u flag seems best... testing out converting parser to use that method
WIP in dirty branch here: https://github.com/chrisputnam9/hjson-php/tree/feature/testing-large-file

If it works well and passes tests, I'll do a PR when done!

**Comment by chrisputnam9** [comment]
Promising results so far.  Passing all tests, and down from ~27 seconds to 180 ms on a 1000 lines of JSON.

Hope to submit PRs this week.

**Comment by dqsully** [comment]
This is amazing, thanks for all your work on this! I'm busy today still but I look forward to seeing your PR when it's ready! And seriously though, huge thanks for doing this.
