### ISSUE TITLE
Multiline strings where a line is just 0 gets truncated

### ISSUE THREAD

**Issue by Aquilosion** [hjson/hjson-php#38]
Given the following JSON:
```
{
  "foo": "bar\n0"
}
```
Converting this to HJSON using `HJSONStringifier` results in:
```
{
  foo:
    '''
    bar

    '''
}
```
The line with `0` gets removed completely, including the indentation.

It looks like the culprit is [this if statement](https://github.com/hjson/hjson-php/blob/dc722dabdd06eaf0ba533e1f007e9f2d23bcb5f6/src/HJSON/HJSONStringifier.php#L171) whose purpose I assume is to not include indentation for empty lines.

[Removing the if statement](https://github.com/hjson/hjson-php/compare/master...Aquilosion:hjson-php:master) such that the conditional block always runs appears to fix it. It'll include indentation for empty lines, though I'd personally prefer that anyway.

**Comment by trobro** [comment]
Thanks for debugging! I'll fix the erroneous check for empty content, but keep the behavior of skipping indentation for empty lines. Changing the behavior might break someone else's use case. And hjson-go, hjson-cpp etc also skip indentation for empty lines.
