### ISSUE TITLE
Parse into array

### ISSUE THREAD

**Issue by cdarken** [hjson/hjson-php#5]
How can I get arrays instead of objects ?

**Comment by cdarken** [comment]
I think I found a solution.
This seems to work:

```
$parser = new HJSONParser();
$jsonData = $parser->parse($json);
$arrays = json_decode(json_encode($jsonData), true);
```

Can you think of a caveat in this case?

**Comment by laktak** [comment]
`parse()` already returns an array:

```
$hjsonText="[1,2,3]";
$parser = new HJSONParser();
$v = $parser->parse($hjsonText);
print_r($v);
```

prints:
```
Array
(
    [0] => 1
    [1] => 2
    [2] => 3
)
```

**Comment by cdarken** [comment]
Not if you have something more complex, like this:
```
{"some_key":"a","some_other_key":"b","settings":{"required":false}}
```
This will get parsed to this (output from var_dump):
```
object(stdClass)#809 (3) {
  ["some_key"]=>
  string(1) "a"
  ["some_other_key"]=>
  string(1) "b"
  ["settings"]=>
  object(stdClass)#813 (1) {
    ["required"]=>
    bool(false)
  }
}
```

**Comment by laktak** [comment]
Ah, I see. I'm not a PHP dev, this repo was contributed by @iainhallam and @jawb. Is the idiomatic php way to use arrays instead of objects?

**Comment by cdarken** [comment]
Yes, usually we work with arrays. Also, I think the arguments should emulate the ones of json_decode.

**Comment by laktak** [comment]
@iainhallam Would you be OK with changing the API to arrays?

@cdarken Would you be willing to do a PR or do you know someone who would?

**Comment by cdarken** [comment]
I wouldn't say changing, just add an option to allow also arrays.
I will try, if I get some time.

**Comment by 4cc355-d3n13d** [comment]
Hey, this works fine for me:

$hjsonText="{"some_key":"a","some_other_key":"b","settings":{"required":false}}";
$parser = new HJSONParser();
$v = (array)$parser->parse($hjsonText);
print_r($v);

**Comment by cdarken** [comment]
@4cc355-d3n13d it doesn't, the "setting" key has a stdClass instance as value, it should be array

**Comment by laktak** [comment]
also see #7

**Comment by 4cc355-d3n13d** [comment]
@cdarken parse the array recursively

**Comment by laktak** [comment]
This is now implemented, thanks @nichtich !
