### ISSUE TITLE
Cirillic chars in comments breaks script

### ISSUE THREAD

**Issue by 4cc355-d3n13d** [hjson/hjson-php#6]
Throws different errors...

Fatal error: Uncaught HJSON\HJSONException: End of input while parsing an array (did you forget a closing ']'?) at line 19, 30 >>>9,

**Comment by 4cc355-d3n13d** [comment]
Cannot use any unicode chars at all, even encoded! =(((

**Comment by laktak** [comment]
Thanks for the report! We are looking for a PHP developer (see #7). Would you be interested in doing a PR?

**Comment by aVadim483** [comment]
@4cc355-d3n13d If you need decode only you can use the alternative implementation: https://github.com/aVadim483/hjson-php

**Comment by biziclop** [comment]
Retarded solution:  
I had to add a specific number of `]` or `space` at the end of the hjson file. Weird. :)

**Comment by Ronef** [comment]
In my case, unicode characters in a multiline string cause the same errors.

@biziclop Many thanks! Today, 3 years later, space at the end of the hjson file still works and helps me 🙂

But what about fixing it?

**Comment by Ronef** [comment]
@4cc355-d3n13d @biziclop I've fixed it, lets test.

**Comment by trobro** [comment]
Is fixed, probably by #19.
